const Widgets = [
  {
    title: "asas",
    description: "sasa",
    id: 1,
    rating: 10,
    date: "sa",
    created: "sa",
    updates: "sas",
    isSpeacialCard: false,
  }, {
    title: "asas",
    description: "sasa",
    id: 2,
    rating: 10,
    date: "sa",
    created: "sa",
    updates: "sas",
    isSpeacialCard: false,
  }, {
    title: "asas",
    description: "sasa",
    id: 3,
    rating: 10,
    date: "sa",
    created: "sa",
    updates: "sas",
    isSpeacialCard: false,
  }, {
    title: "asas",
    description: "sasa",
    id: 4,
    rating: 10,
    date: "sa",
    created: "sa",
    updates: "sas",
    isSpeacialCard: false,
  }, {
    title: "asas",
    description: "sasa",
    id: 5,
    rating: 10,
    date: "sa",
    created: "sa",
    updates: "sas",
    isSpeacialCard: false,
  },
];
export { Widgets };